# Week 1 — Session 2
## Probability & Sampling Basics

### Goals
- Understand probability as a measure of uncertainty
- Work with events and conditional probability
- Distinguish P(A|B) from P(B|A)
- Use Boolean operations in Pandas
- Apply probability concepts to an urban dataset

In [2]:
import pandas as pd
import numpy as np

## Example Dataset

Each row represents one hypothetical neighborhood.

Variables:
- district
- land_use
- metro_access

In [3]:
data = {
    "district": ["A","B","C","D","E","F","G","H","I","J"],
    "land_use": [
        "Residential",
        "Commercial",
        "Residential",
        "Administrative",
        "Residential",
        "Commercial",
        "Residential",
        "Administrative",
        "Commercial",
        "Residential"
    ],
    "metro_access": [
        True, True, False, True, False,
        True, False, True, False, True
    ]
}

df = pd.DataFrame(data)

df

  district        land_use  metro_access
0        A     Residential          True
1        B      Commercial          True
2        C     Residential         False
3        D  Administrative          True
4        E     Residential         False
5        F      Commercial          True
6        G     Residential         False
7        H  Administrative          True
8        I      Commercial         False
9        J     Residential          True

## Simple Probability

Probability can be estimated from observed proportions.

Example:

P(Metro Access)

In [4]:
p_metro = df["metro_access"].mean()

print("P(Metro Access) =", p_metro)

P(Metro Access) = 0.6

In [5]:
df["land_use"].value_counts()

land_use
Residential       5
Commercial        3
Administrative    2
Name: count, dtype: int64

## Probability of an Event

There are 3 Commercial neighborhoods among 10 observations.

Therefore:

P(Commercial) = 3 / 10 = 0.3

In [6]:
p_commercial = (df["land_use"] == "Commercial").mean()

print("P(Commercial) =", p_commercial)

P(Commercial) = 0.3

## Conditional Probability

We now estimate:

P(Metro Access | Commercial)

Meaning:

Among Commercial neighborhoods, what proportion has metro access?

In [7]:
commercial = df[df["land_use"] == "Commercial"]

commercial

  district    land_use  metro_access
1        B  Commercial          True
5        F  Commercial          True
8        I  Commercial         False

In [8]:
p_metro_given_commercial = commercial["metro_access"].mean()

print(
    "P(Metro Access | Commercial) =",
    p_metro_given_commercial
)

P(Metro Access | Commercial) = 0.6666666666666666

## Important Interpretation

P(Metro | Commercial) does not mean:

P(Commercial | Metro)

Conditional probability has direction.

In [9]:
metro = df[df["metro_access"] == True]

p_commercial_given_metro = (
    metro["land_use"] == "Commercial"
).mean()

print(
    "P(Commercial | Metro) =",
    p_commercial_given_metro
)

P(Commercial | Metro) = 0.3333333333333333

## Independence

Two events are independent if:

P(A | B) = P(A)

Equivalently:

P(A ∩ B) = P(A) × P(B)

We should not assume independence without checking.

In [10]:
p_metro = df["metro_access"].mean()

p_metro_given_commercial = (
    df[df["land_use"] == "Commercial"]["metro_access"].mean()
)

print("P(Metro) =", p_metro)
print(
    "P(Metro | Commercial) =",
    p_metro_given_commercial
)

P(Metro) = 0.6
P(Metro | Commercial) = 0.6666666666666666

### Interpretation

P(Metro) and P(Metro | Commercial) are different in this small dataset.

This suggests that Metro Access and Commercial Land Use are not behaving as independent events in this sample.

This does NOT prove causation.

## Random Variable

A random variable converts uncertain outcomes into numerical values.

For example:

X = number of neighborhoods with Metro Access

In [11]:
metro_count = df["metro_access"].sum()

print(
    "Number of neighborhoods with Metro Access:",
    metro_count
)

Number of neighborhoods with Metro Access: 6

# Tehran Project Connection

Raw counts can be misleading.

For public-space analysis, a district with more parks may also have:
- more population
- larger area

Therefore we may need normalization.

In [12]:
urban_data = pd.DataFrame({
    "district": ["A", "B", "C"],
    "population": [50000, 100000, 75000],
    "area_km2": [5, 8, 6],
    "parks": [10, 16, 12]
})

urban_data

  district  population  area_km2  parks
0        A       50000         5     10
1        B      100000         8     16
2        C       75000         6     12

In [13]:
urban_data["parks_per_10000_people"] = (
    urban_data["parks"]
    / urban_data["population"]
    * 10000
)

urban_data["parks_per_km2"] = (
    urban_data["parks"]
    / urban_data["area_km2"]
)

urban_data

  district  population  area_km2  parks  parks_per_10000_people  parks_per_km2
0        A       50000         5     10                     2.0            2.0
1        B      100000         8     16                     1.6            2.0
2        C       75000         6     12                     1.6            2.0

## Interpretation

Raw park count answers:

"How many parks are there?"

Parks per population answers:

"How much park availability exists relative to residents?"

Parks per area answers:

"How spatially dense are parks?"

These are different urban questions.

# Independent Exercise

Using the dataset above:

1. Find the district with the highest number of parks.
2. Find the district with the highest parks per 10,000 people.
3. Find the district with the highest parks per km².
4. Explain why the three answers may differ.

# Session Summary

Key concepts:

- Probability represents uncertainty.
- Events can be measured using proportions.
- Conditional probability depends on direction.
- P(A|B) is not the same as P(B|A).
- Independence must be tested, not assumed.
- Probability does not imply causation.
- Urban indicators often require normalization.